name: Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      containerUser: ${{ steps.get-user.outputs.containerUser }}

    steps:
      - id: get-user
        run: echo "::set-output name=containerUser::`id -u`:`id -g`"

  integration-tests:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/quantum/iqsharp-base:latest
      options: --user ${{ needs.configure.outputs.containerUser }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel pytest pytest-cov pytest-mock flaky --upgrade

      - name: Install Plugin
        run: |
          python setup.py bdist_wheel
          pip install dist/PennyLane*.whl

      - name: Run tests
        run: |
          pytest /github/home/.local/lib/python3.7/site-packages/pennylane/devices/tests --device=microsoft.simulator --tb=short --skip-ops --analytic=False --shots=20000 --cov=pennylane_qsharp --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
